# Generated by Django 5.1.6 on 2025-02-16 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_remove_doctorschedule_doctor_delete_doctor_and_more'),
        ('patient', '0002_patient_latitude_patient_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambulancerequest',
            name='ambulance',
        ),
        migrations.AddField(
            model_name='ambulancerequest',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ambulance_requests', to='hospital.hospital'),
        ),
    ]
