# Generated by Django 5.1.6 on 2025-02-16 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_remove_doctorschedule_doctor_delete_doctor_and_more'),
        ('patient', '0003_remove_ambulancerequest_ambulance_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ambulance',
        ),
        migrations.AlterField(
            model_name='ambulancerequest',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambulance_requests', to='hospital.hospital'),
        ),
    ]
