# Generated by Django 5.1.6 on 2025-02-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_delete_ambulance_alter_ambulancerequest_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulancerequest',
            name='reason',
            field=models.TextField(default='No reason provided'),
        ),
    ]
