# Generated by Django 5.1.6 on 2025-02-13 08:19

import django.db.models.deletion
import shea.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbulanceDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('license_number', models.CharField(max_length=5)),
                ('password', models.CharField(default='null', max_length=255)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospitaldb')),
            ],
            options={
                'verbose_name': 'Ambulance Driver',
                'verbose_name_plural': 'Ambulance Drivers',
            },
        ),
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('registration_number', models.CharField(max_length=50)),
                ('hospital', models.ForeignKey(blank=True, default=shea.models.get_default_hospital, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.hospitaldb')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shea.ambulancedriver')),
            ],
        ),
    ]
